# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1.4.3
    - name: Set up JDK 11
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  cd:
    
    runs-on: ubuntu-latest
    
    needs: ci

    steps:
       - uses: actions/checkout@v1
       - name: Docker login
         run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
       - name: Build
         run: docker build -t quay.io/${{ secrets.DOCKER_USER }}/kafka-streams-convert-base64-app .
       - name: Tags
         run: |
           docker tag quay.io/${{ secrets.DOCKER_USER }}/kafka-streams-convert-base64-app:${{ github.sha }}
           docker tag quay.io/${{ secrets.DOCKER_USER }}/kafka-streams-convert-base64-app:latest
       - name: Push
         run: |
           docker push quay.io/${{ secrets.DOCKER_USER }}/kafka-streams-convert-base64-app:${{ github.sha }}
           docker push quay.io/${{ secrets.DOCKER_USER }}/kafka-streams-convert-base64-app:latest
